---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - external_storage_device_id is defined

- name: Mount up device by UUID
  ansible.posix.mount:
    path: /mnt
    src: "UUID={{external_storage_device_id}}"
    fstype: ext4
    state: present
